aws_region = "us-east-2"
environment = "dev"
bucket_name = "hypha-portfolio"
portfolio_description = "vpc"
portfolio_name = "vpc"
product_name = "vpc-config"
product_owner = "Kiran"
provider_name = "Kiran"